baseURL = "https://example.com"
title = "Catherine Cusick"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "A summary of Catherine Cusick's tax credentials."
  copyright = "Copyright © 2023 Catherine Cusick"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "intro"
    name = "intro"
    title = "intro"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "credentials"
    name = "credentials"
    title = "credentials"
    url = "/credentials/"
    weight = 20

  [[menu.main]]
    identifier = "credits"
    name = "credits"
    title = "credits"
    url = "/credits/"
    weight = 30

  [[menu.main]]
    identifier = "tech"
    name = "tech"
    title = "tech"
    url = "/tech/"
    weight = 40

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true